Feature/Initialize Azure Map
Mentoring-Bordeaux/AutonomousCars pull request #28
Opened 2023-11-10 15:40 UTC by fbour33

Installation du module azure-maps-control via pnpm
Création d'un composant background pour initialiser la carte
Changement du index.vue pour intégrer la carte sur la page de garde

2023-11-10 16:00 UTC, theogom requested changes

2023-11-10 16:00 UTC, theogom commented on src/front/components/map/background.vue
> +                        subscriptionKey: "76c6F3ZTQ9iJDRo20oAU-D5YtyP7wkG-s1BRffLLgbc"
Il faudrait stocker la clé dans un fichier d'environnement, voir [Microsoft Learn - Azure Maps - Secure a daemon application](https://learn.microsoft.com/en-us/azure/azure-maps/how-to-secure-daemon-app)

2023-11-10 16:00 UTC, theogom commented on src/front/components/map/background.vue
> +<script lang="ts">
Préférer la [Composition API](https://vuejs.org/api/composition-api-setup.html) plutôt que l'[Option API](https://vuejs.org/guide/typescript/options-api.html#typescript-with-options-api).
Pour les lifecycle hooks voir [Composition API: Lifecycle Hooks](https://vuejs.org/api/composition-api-lifecycle.html#composition-api-lifecycle-hooks).

2023-11-15 18:47 UTC, theogom commented on src/front/components/map/background.vue
> +                        subscriptionKey: "76c6F3ZTQ9iJDRo20oAU-D5YtyP7wkG-s1BRffLLgbc"
Pour les variables d'environnement, il faut en fait les référencer dans le fichier `nuxt.config.ts` et y accéder avec la runTimeConfig, voir [Nuxt - Runtime Config](https://nuxt.com/docs/guide/going-further/runtime-config).

2023-11-16 08:24 UTC, theogom approved these changes

2023-11-17 10:51 UTC, cbonnaud001 approved these changes

2023-11-20 13:17 UTC, merged