Feature/mqtt receive data and emulate it
Mentoring-Bordeaux/AutonomousCars pull request #60
Opened 2024-01-08 10:48 UTC by tgaignard001

Cette feature permet d'avoir un émulateur qui reçoit un GeoJson LineString et émule les points reçus.

On a également développé un endpoint qui permet d'envoyer un Geojson du bakc vers l'émulateur sur le topic itinerary/#
Cet endpoint sert surtout de test pour l'instant et a pour but d'être fusionné avec le endpoint des itinéraires

2024-01-09 13:36 UTC, TechWatching requested changes

2024-01-09 13:36 UTC, TechWatching commented on src/api/AutonomousCars.Api/Models/TimePosition.cs
Partager les différents modèles entre emulateur et API en les mettant dans un projet (csproj) ) part qui soit référencé dans l'émulateur et l'API.

2024-01-09 13:36 UTC, TechWatching commented on src/api/AutonomousCars.Api/Itinerary/Services/IWorker.cs
A supprimer

2024-01-09 13:36 UTC, TechWatching commented on src/api/AutonomousCars.Api/Itinerary/Services/Worker.cs
> +public class Worker : BackgroundService, IWorker
Ne pas utiliser BackgroundService ou IWorker. Cela sert dans le cadre d'une application console ou si l'on veut faire un service qui tourne en arrière plan et traite des messages ou autre. Le service que l'on veut ici est appelé directement par le controlleur.

Il faudrait donc transformer cette classe en AzureMapsItineraryService qui implémente un IItineraryService

2024-01-09 13:36 UTC, TechWatching commented on src/api/AutonomousCars.Api/Controllers/ItineraryController.cs
> +    public async Task<IActionResult> SendItinerary()
Ca ne devrait pas prendre l'id du véhicule en paramètre ?

2024-01-09 13:36 UTC, TechWatching commented on src/api/AutonomousCars.Api/Itinerary/Services/Worker.cs
> +    public async Task ExecuteAsyncPublic(CancellationToken stoppingToken, bool isStatusRequest)
nom de méthode pas parlant

2024-01-09 13:36 UTC, TechWatching commented on src/emulator/Worker.cs
> +        if (await _handleSemaphore.WaitAsync(TimeSpan.Zero, stoppingToken))
Pourquoi ne pas plutôt rejeter la requête / ne rien faire si le statut du véhicule est déjà "occupé", "en course" ou quelque chose comme ça.

2024-01-09 15:18 UTC, tgaignard001 commented on src/emulator/Worker.cs
> +        if (await _handleSemaphore.WaitAsync(TimeSpan.Zero, stoppingToken))
Comme l'appel à la fonction Handle se fait de manière asynchrone, je me suis dit que ce n'était pas très propre de faire juste un booléen status parce qu'on peut avoir des accès concurrents dessus, d'où mon utilisation d'un sémaphore.

2024-01-09 21:31 UTC, victorlohezic commented on src/api/AutonomousCars.Api/Controllers/ItineraryController.cs
> +    public async Task<IActionResult> SendItinerary()
Je ne savais pas encore ce que le front allait transmettre, j'ai donc changé pour que ça prenne un paramètre du type Feature<LineString>

2024-01-10 15:41 UTC, tgaignard001 commented on src/api/AutonomousCars.Api/Models/TimePosition.cs
C'est fait, on a créé le projet Utils mais il contient que des méthodes utiles pour les manipulations de GeoJson mais pas de Classes car finalement on utilise du GeoJson

2024-01-11 08:08 UTC, TechWatching commented on src/emulator/Worker.cs
> +        if (await _handleSemaphore.WaitAsync(TimeSpan.Zero, stoppingToken))
En fait au delà de l'utilisation du sémaphore, je me disais qu'on pouvait directement rejeter car le véhicule est occupé plutôt que d'attendre pour traiter la requête. Mais bon ça me va comme ça pour le moment.

2024-01-11 08:10 UTC, TechWatching approved these changes

2024-01-12 14:39 UTC, merged