Feature/migrate dotnet 8 ga
Mentoring-Bordeaux/AutonomousCars pull request #61
Opened 2024-01-08 15:20 UTC by tgaignard001

Je ne sais pas si c'est cela qu'il fallait faire pour migrer la version de .NET mais du coup j'ai ajouté les packages dans les solutions

2024-01-09 11:31 UTC, TechWatching approved these changes

2024-01-09 11:31 UTC, TechWatching commented on src/emulator/AutonomousCars.Emulator.csproj
> +		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
Changer également Microsoft.Extensions.Hosting en 8

2024-01-09 11:31 UTC, TechWatching commented on src/emulator/Worker.cs
> +
espace inutile

2024-01-09 13:39 UTC, TechWatching requested changes

2024-01-09 13:39 UTC, TechWatching commented on src/api/AutonomousCars.Api/AutonomousCars.Api.sln
déjà un sln à la racine, pas besoin de celui là

2024-01-09 13:39 UTC, TechWatching commented on src/azure_function/Company.FunctionTelemetry/Company.FunctionTelemetry/Company.FunctionTelemetry.csproj
>          <Nullable>enable</Nullable>
Je pense que tu as ajouté des packages dans des projets où ils ne servent pas.

2024-01-10 16:12 UTC, tgaignard001 commented on src/azure_function/Company.FunctionTelemetry/Company.FunctionTelemetry/Company.FunctionTelemetry.csproj
>          <Nullable>enable</Nullable>
j'ai essayé d'en supprimer mais je crois que tout est utilisé

2024-01-10 16:12 UTC, tgaignard001 commented on src/api/AutonomousCars.Api/AutonomousCars.Api.sln
j'ai supprimé

2024-01-10 16:15 UTC, tgaignard001 commented on src/emulator/AutonomousCars.Emulator.csproj
> +		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
C'est bon j'ai changé

2024-01-11 21:28 UTC, TechWatching commented on src/azure_function/Company.FunctionTelemetry/Company.FunctionTelemetry/Company.FunctionTelemetry.csproj
>          <Nullable>enable</Nullable>
Mon commentaire est mal placé. C'était plus sur le csproj de l'émulateur que ça doit pas servir.

2024-01-12 13:46 UTC, TechWatching approved these changes

2024-01-12 15:24 UTC, cbonnaud001 approved these changes

2024-01-14 09:37 UTC, merged