Feature/list all devices front back
Mentoring-Bordeaux/AutonomousCars pull request #62
Opened 2024-01-08 20:45 UTC by victorlohezic

Ajout de la bibliothèque pinia pour pouvoir stocker tous les véhicules et y accéder depuis tous les composants. J'y ai ajouté une fonction pour interroger le back et récupérer la liste des véhicules du parc. Cependant, le temps de réponse étant long, j'ai ajouté un loader.

2024-01-09 09:15 UTC, cbonnaud001 commented on src/front/components/vehicles/card.vue
> +const vehicle = props.vehicle;
Pourquoi est-ce que tu différencie vehicule et props.vehicule ? Dans le template tu peux directement accéder au vehicule des props sans avoir besoin de spécifier le .props

2024-01-09 09:18 UTC, cbonnaud001 commented on src/front/components/vehicles/cardList.vue
> +const type = ref(props.type)
Je suis surpris que le compilo ne rale pas, je pensais que "type" était un reserved keyword pour typescript. Dans tous les cas, étant donné que tu n'utilises props.type uniquement en lecture, tu n'as pas besoin de créer une ref, la réactivité est préservée via le props de base si je ne dis pas de bêtise

2024-01-09 09:18 UTC, cbonnaud001 commented on src/front/components/vehicles/cardList.vue
> +  console.log("type " + type.value);
Pense à retirer les console.log

2024-01-09 09:27 UTC, cbonnaud001 requested changes

2024-01-09 09:27 UTC, cbonnaud001 commented on src/front/components/vehicles/card.vue
> +const props = defineProps(['vehicle']);
la syntaxe d'utilisation du defineProps n'est pas la même qu'ailleurs, il faudrait que ce soit homogène

2024-01-09 09:27 UTC, cbonnaud001 commented on src/front/components/vehicles/cardList.vue
> +const shouldDisplayVehicle = (vehicle: Vehicle): Boolean => {
C'est une bonne pratique de n'utiliser que les types primitifs, sauf exception bien précise. 
https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#the-primitives-string-number-and-boolean

2024-01-09 09:27 UTC, cbonnaud001 commented on src/front/components/vehicles/cardList.vue
> +const shouldDisplayVehicle = (vehicle: Vehicle): Boolean => {
Pareil que précédemment, dans le code on a des arrow functions et des functions, il faudrait que ce soit homogène

2024-01-09 09:27 UTC, cbonnaud001 commented on src/front/components/vehicles/content.vue
> +      <div v-if=useVehiclesListStore().isLoaded v-for="(_, index) in tabContents" :key="index" v-show="activeTab === index" class="h-125 overflow-y-scroll">
Attention, il faut éviter d'utiliser v-if et v-show sur le même élément 
https://vuejs.org/guide/essentials/conditional.html#v-if-with-v-for

2024-01-09 09:27 UTC, cbonnaud001 commented on src/front/stores/vehiclesList.ts
> +              this.vehiclesList.push(vehicleLocation);
Tu peux utiliser un map ici au lieu de faire un for et un push

2024-01-09 11:29 UTC, TechWatching requested changes

2024-01-09 11:29 UTC, TechWatching commented on src/front/stores/vehiclesList.ts
> +          const response = await fetch('/api/ListingDevices/getAllDevices');
Préférer l'utilisation de useFetch https://nuxt.com/docs/api/composables/use-fetch

2024-01-09 13:48 UTC, TechWatching commented on src/front/components/vehicles/cardList.vue
> +var vehiclesList = useVehiclesListStore().vehiclesList
Ne pas utiliser var, toujours const ou let.
Je pense qu'il faudrait plutôt passer la vechicleList en prop de ce composant (plutôt que de passer son type).

2024-01-11 15:33 UTC, rebeccapnt approved these changes

2024-01-11 15:33 UTC, fboitel approved these changes

2024-01-11 16:55 UTC, cbonnaud001 approved these changes
On pourra discuter rapidement de 2-3 passages demain en séance, mais c'est plus de la forme que du fond

2024-01-11 21:59 UTC, TechWatching approved these changes
J'ai fait quelques commentaires

2024-01-11 21:59 UTC, TechWatching commented on src/api/AutonomousCars.Api/Controllers/ListingDevicesController.cs
> +        string subscriptionId = _mqttNamespaceOptions.SubscriptionId ?? throw new MissingSettingException($"{nameof(MqttNamespaceOptions)}.{nameof(MqttNamespaceOptions.SubscriptionId)}");
C'est pas très grave si tu le changes pas mais pour info ce genre de validation ça se fait plutôt ailleurs dans le code (injection de dépendance, Program.cs)

2024-01-11 21:59 UTC, TechWatching commented on src/api/AutonomousCars.Api/Device/Services/MqttDevices.cs
> +    public async Task<List<String>> GetDeviceNames(string subscriptionId, string resourceGroupName, string namespaceName)
J'aurais plutôt injecté l'options dans le constructeur de ce service plutôt que de passer tout ça en paramètre jusqu'à ce service.

2024-01-11 21:59 UTC, TechWatching commented on src/api/AutonomousCars.Api/Program.cs
> +        builder.Services.Configure<MqttNamespaceOptions>(builder.Configuration.GetSection("MqttNamespace"));
Ici tu dois pouvoir ajouter de la validation si tu veux vraiment vérifier qu'on a bien toute la configuration (pas obligé de t'embêter à faire ça). L'utilisation de Options convient très bien ici, par contre la configuration tu la mets via les user secrets ce qui veut dire que ça ne marchera qu'en local et pas sur Azure. Donc il faudrait plutôt ajouter les secrets dans un [Azure Key Vault de manière à ce qu'ils soient disponibles dans la configuration](https://learn.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-8.0#use-managed-identities-for-azure-resources).

2024-01-11 21:59 UTC, TechWatching commented on src/front/components/vehicles/content.vue
> +    return vehiclesListStore.vehiclesList.filter((vehicle) =>  vehicle.available == true);
Juste `=> vehicle.available` et `=> !vehicle.available` en dessous. Ce sont déjà des booléens

2024-01-11 22:00 UTC, TechWatching commented on src/front/stores/vehiclesList.ts
> +      await useFetch('/api/ListingDevices/getAllDevices', {
Pas la bonne utilisation de useFetch. Cf https://www.youtube.com/watch?v=njsGVmcWviY
Soit tu utilises $fetch. Soit tu fais le usefetch à l'exérieur de ton action initVehiclesDevices et tu appeles le execute de usefetch dans ton action.

2024-01-11 22:01 UTC, TechWatching commented on src/front/stores/vehiclesList.ts
> +  state: () => ({
Je pensais que ça aurait été plus uniforme avec le reste de mettre le store en script setup

2024-01-12 13:47 UTC, merged